- hosts: workstation
  gather_facts: true
  # Collect osp facts
  roles:
     - name: osp-facts
  tags:
     - inv

# Setup load-balancer
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - general-config
    - lb-tier
  tags:
    - lb

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - general-config
    - app-tier
  tags:
    - app

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - general-config
    - db-tier
  tags:
    - db
