- name: Provision OSP instances
  hosts: workstation
  become: yes
  tasks:
    - name: Create app1 instance
      include_role:
        name: osp-servers 
      vars:
        instance_name: app1

#    - name: Create appr2 instance
#      include_role:
#        name: osp-servers 
#        vars_from: app2.yml
#      vars:
#        instance_name: app2
#
#    - name: Create db instance
#      include_role:
#        name: osp-servers 
#        vars_from: db.yml
#      vars:
#        instance_name: db 
#
#    - name: Create frontend instance
#      include_role:
#        name: osp-servers
#        vars_from: frontend.yml
#      vars:
#        instance_name: frontend 
