---
# tasks file for lb-tier
- name: Install configuration file for HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    notify: 
      - restart_haproxy
  tags:
  - HAconfig    
