---
# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Add host 1
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      ansible_ssh_extra_args: " -F ssh.cfg "
      # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      # ansible_ssh_user: cloud-user
     with_items: "{{result.ansible_facts.openstack_servers}}"
   - name: Add host 2
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
      ansible_ssh_extra_args: " -F ~/.ssh/ssh.cfg "

      #      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      #  ansible_ssh_user: cloud-user
     with_items: "{{result.ansible_facts.openstack_servers}}"
