---
# tasks file for app-tier

- name: Install Tomcat 
  yum:
    name: "tomcat"
    state: latest

- name: create tomcat default web directory
  file:
    path: "/usr/share/tomcat/webapps/ROOT"
    state: directory
    mode: 0775

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "/usr/share/tomcat/webapps/ROOT/index.html"
    mode: 0644
- name: Enable  Tomcat 
  service:
    name: "tomcat"
    enabled: yes

- name: Restart tomcat
  service:
    name: "tomcat"
    state: restarted
  tags:
  - restart_tomcat  
